%YAML:1.0

time_window: ["1403636649313555456", "1403636658963555584"]   # initial trial
# time_window: ["1403636665000000000", "1403636700000000000"]    
# time_window: ["1403636665000000000", "1403636722000000000"]     # from ground_truth_process, finally put in the paper

frontend:
  downsample_rate: 8
  landmark_obs_count_threshold: 4

backend:
  tri_max_num_iterations: 16   # triangularization